import MSWBootstrap from '@/app/providers/msw-bootstrap';
import { AppProviders } from '@/app/providers/app-providers';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import '@/app/styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: 'Create Next App',
  description: 'Generated by create next app',
  alternates: {
    canonical: './',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <MSWBootstrap>
          <AppProviders>{children}</AppProviders>
        </MSWBootstrap>
      </body>
    </html>
  );
}
