import MSWBootstrap from '@/app/providers/msw-bootstrap';
import { AppProviders } from '@/app/providers/app-providers';
import { pretendard } from '@/shared/fonts';

import type { Metadata } from 'next';

import '@/app/styles/globals.css';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: 'Create Next App',
  description: 'Generated by create next app',
  alternates: {
    canonical: './',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <div className="root flex min-h-full flex-1 flex-col">
          <MSWBootstrap>
            <AppProviders>{children}</AppProviders>
          </MSWBootstrap>
        </div>
      </body>
    </html>
  );
}
