name: "cd"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  cd:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/pnpm-setup-node

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::953138073651:role/github-actions-role

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      #   - name: Sync static files with S3
      #     env:
      #       MAX_AGE: ${{ vars.CACHE_CONTROL_MAX_AGE }}
      #     run: aws s3 sync .next/static s3://${{ vars.S3_BUCKET }}/${{ github.sha }}/_next/static --cache-control max-age=$MAX_AGE,public,immutable

      - name: build docker image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --platform linux/amd64 \
            -f docker/Dockerfile \
            -t "$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" .
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nextjs-ecs-container
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: nextjs-ecs-task-service
          cluster: nextjs-ecs-cluster
          wait-for-service-stability: true
