name: "ci"

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  statuses: write

jobs:
  ci:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/pnpm-setup-node

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build
